//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clipMoney.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Billetera_ElectronicaEntities : DbContext
    {
        public Billetera_ElectronicaEntities()
            : base("name=Billetera_ElectronicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barrios> Barrios { get; set; }
        public virtual DbSet<Cuentas> Cuentas { get; set; }
        public virtual DbSet<CuentaTipo> CuentaTipo { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<Monedas> Monedas { get; set; }
        public virtual DbSet<Operaciones> Operaciones { get; set; }
        public virtual DbSet<PagoFacturas> PagoFacturas { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<PlazosFijos> PlazosFijos { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<ServiciosTipo> ServiciosTipo { get; set; }
        public virtual DbSet<TipoOperacion> TipoOperacion { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
