//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clipMoney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operaciones
    {
        public int id_transferencia { get; set; }
        public int CVU_cuenta { get; set; }
        public Nullable<int> CVU_cuenta_destino { get; set; }
        public Nullable<int> CVU_cuenta_origen { get; set; }
        public Nullable<bool> verificacion_banco { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_ocurrencia { get; set; }
        public double monto_original { get; set; }
        public Nullable<double> monto { get; set; }
        public int id_tipo_operacion { get; set; }
        public Nullable<bool> verificacion_origen_destino { get; set; }
        public Nullable<int> id_moneda { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual TipoOperacion TipoOperacion { get; set; }
    }
}
