//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clipMoney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoFacturas
    {
        public int numero_factura { get; set; }
        public int id_servicio { get; set; }
        public bool estado { get; set; }
        public System.DateTime fecha_factura { get; set; }
        public double monto { get; set; }
        public Nullable<int> CVU_cuenta { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
