//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clipMoney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlazosFijos
    {
        public int id_plazo_fijo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public double monto_ingresado { get; set; }
        public double monto_salida { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_finalizacion { get; set; }
        public Nullable<int> CVU_cuenta { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
    }
}
